packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - esbuild
  - sharp

ignoredBuiltDependencies:
  - bufferutil
  - utf-8-validate

catalog:
  typescript: ^5.9.2
  vitest: ^3.2.4

allowBuilds:
  esbuild: true
  sharp: true
